MEDIOClinic/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using CMS.Membership;
using CMS.Search;

namespace MEDIOClinic.Controllers
{
    public class SearchController : Controller
    {
        // Adds the smart search indexes that will be used to perform searches
        public static readonly string[] searchIndexes = new string[] { "MEDIOClinic" };
        // Sets the limit of items per page of search results
        private const int PAGE_SIZE = 10;



        public ActionResult SearchIndex(string searchText)
        {
            // Displays the search page without any search results if the query is empty
            if (String.IsNullOrWhiteSpace(searchText))
            {
                // Creates a model representing empty search results
                SearchResultModel emptyModel = new SearchResultModel
                {
                    Items = new List<SearchResultItem>(),
                    Query = String.Empty
                };

                return View(emptyModel);
            }

            // Searches the specified index and gets the matching results
            SearchParameters searchParameters = SearchParameters.PrepareForPages(searchText, searchIndexes, 1, PAGE_SIZE, MembershipContext.AuthenticatedUser);
            SearchResult searchResult = SearchHelper.Search(searchParameters);

            // Creates a model with the search result items
            SearchResultModel model = new SearchResultModel
            {
                Items = searchResult.Items,
                Query = searchText
            };

            return View(model);
        }
    }
}

MEDIOClinic/ViewComponents/NavigationMenuViewComponent.cs
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Mvc;

using CMS.Core;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Routing;

using Kentico.Content.Web.Mvc;

using MEDIOClinic.Models;

namespace CoreTutorial.ViewComponents
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly IPageRetriever pageRetriever;
        private readonly IPageUrlRetriever pageUrlRetriever;

        public NavigationMenuViewComponent(IPageRetriever pageRetriever, IPageUrlRetriever pageUrlRetriever)
        {
            // Initializes instances of required services using dependency injection
            this.pageRetriever = pageRetriever;
            this.pageUrlRetriever = pageUrlRetriever;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Retrieves a collection of page objects with data for the menu (pages of all page types)
            IEnumerable<TreeNode> menuItems = await pageRetriever.RetrieveAsync<TreeNode>(query => query
                                                    // Selects pages that have the 'Show in menu" flag enabled
                                                    .MenuItems()
                                                    // Only loads pages from the first level of the site's content tree
                                                    .NestingLevel(1)
                                                    // Filters the query to only retrieve required columns
                                                    .Columns("DocumentName", "NodeID", "NodeSiteID")
                                                    // Loads pages together with their URL path data (performance reasons)
                                                    .WithPageUrlPaths()
                                                    // Uses the menu item order from the content tree
                                                    .OrderByAscending("NodeOrder"));

            // Creates a collection of view models based on the menu item data
            IEnumerable<MenuItemViewModel> model = menuItems.Select(item => new MenuItemViewModel()
            {
                // Gets the name of the page as the menu item caption text
                MenuItemText = item.DocumentName,
                // Retrieves the URL for the page (as a relative virtual path)
                MenuItemRelativeUrl = pageUrlRetriever.Retrieve(item).RelativePath
            });

            return View(model);
        }
    }
}

MEDIOClinic/Views/Shared/_Layout.cshtml
@using Kentico.OnlineMarketing.Web.Mvc
@using Kentico.Web.Mvc

@using BlankSiteCore.Helpers

@inject IHtmlLocalizer<SharedResources> HtmlLocalizer

@{
    const string ENGLISH = "English";
    const string THAI = "ไทย";

    var currentCultureCode = Convert.ToString(@ViewContext.RouteData.Values["culture"]);
    var currentLanguage = currentCultureCode.Equals("th-TH", StringComparison.OrdinalIgnoreCase) ? "th-TH" : "en-US";
}

<!DOCTYPE html>
<html lang="@currentLanguage">
<head>
    <meta charset="utf-8">
    @Html.Kentico().PageTitle(ViewBag.Title as string)
    @Html.Kentico().PageDescription()
    @Html.Kentico().PageKeywords()
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
    @* Razor section for additional page-specific styles *@
    @RenderSection("styles", required: false)
    @Html.Kentico().WebAnalyticsLoggingScript()

</head>
<body>
    <header>
        <div class="col-sm-offset-3 col-sm-6">
            <div class="col-sm-6">
                @* Targets the root page of the website *@
                <a href="~/@currentLanguage/home" title="MedioClinic homepage" class="logo">MEDIO clinic</a>
            </div>
            <div class="col-sm-6 nav">
                @* Renders the view component with the navigation menu, including the <nav> element *@
                @await Component.InvokeAsync("NavigationMenu")

                @using (Html.BeginForm("SearchIndex", "Search", FormMethod.Get))
                {
                    <input type="text" name="searchtext" placeholder="@HtmlLocalizer["Search..."]" maxlength="1000">
                    <input type="submit" value="@HtmlLocalizer["Search"]">
                }


                <div class="dropdown-content">
                    <culture-link link-text="@ENGLISH" culture-name="en-US" />
                    <culture-link link-text="@THAI" culture-name="th-TH" />
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </header>
    @* Loads the content of your Tutorial's pages as sub views *@
    @RenderBody()
    <footer>
        <div class="col-sm-offset-3 col-sm-6">
            <div class="row">
                <div class="col-sm-6">
                    <h4>MEDIO clinic</h4>
                    <ul>
                        <li><i class="fa fa-map-marker"></i> Address: <address>7A Kentico street, Bedford, NH 03110, USA</address></li>
                        <li><i class="fa fa-envelope-o"></i> E-mail: <a href="mailto:info@medio-clinic.com" title="Email us">info@medio-clinic.com</a></li>
                        <li><i class="fa fa-phone"></i> Phone number: <a href="tel:5417543010" title="Phone us">(541) 754-3010</a>
                    </ul>
                </div>
                <div class="col-sm-6">
                    <span class="cms">Powered by <a href="https://xperience.io/" title="Kentico Xperience CMS">Kentico Xperience CMS for ASP.NET Core</a></span>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </footer>
    @* Razor section for additional page-specific scripts *@
    @RenderSection("scripts", required: false)
</body>
</html>